# CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}
      - run:
          name: Run gradle build tasks
          command: ./gradlew clean build codeCoverageReport
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - persist_to_workspace:
          root: ./
          paths:
            - build
      - store_artifacts:
          path: build/libs
          destination: ./
      - run:
          name: Publish code coverage to codecov.io
          command: bash <(curl -s https://codecov.io/bash)

  deploy:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}
      - attach_workspace:
          at: ./
      - run:
          name: Setup gradle plugins credentials
          command: echo -e $GRADLE_LOGIN > ~/.gradle/gradle.properties
      - run:
          name: Run gradle publish plugins task
          command: ./gradlew publishPlugins
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}

workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
